### ISSUE TITLE
will you be ready for V3?

### ISSUE THREAD

**Issue by Festeazy** [PantryParty/pantry_party#106]

**Comment by arjes** [comment]
Nope!

**Comment by ArchdukeTim** [comment]
@arjes You mentioned in the linked issue that life's kicking your butt, so I'll take a look at this later to try to bring it up to speed. I'm interested in getting the bare bones working (right now it says a response code of 200 is an error :joy: ) and might not worry about getting everything running, but I'll try my best. If there are any pointers you have about things you know are definitely broken I'm all ears.

**Comment by arjes** [comment]
@ArchdukeTim No problem, thank for stepping up. Part of the issue is that there isn't a single damn test, since it stated as a personal project... There is also the issue that this was my first foray into NativeScript :D I have good experience with NG and TS in general, but there is lots of new stuff.

I have not reviewed the 3.0 api, but I expect it is quite different to some fundamental model changes.

**Comment by arjes** [comment]
@ArchdukeTim I've gone ahead and started the `start_v3_upgrade` branch which allows the code to branch between a v3 and a v2 adapter. As of right now I have not checked any functionality besides the first-time-startup

**Comment by arjes** [comment]
A working PantryParty should be on all app stores. I'll make a post in /r/grocy tomorrow.
