### ISSUE TITLE
Differences to barcode buddy

### ISSUE THREAD

**Issue by totti4ever** [PantryParty/pantry_party#56]
Since I know there's an app for barcode buddy, I was wondering where these two apps distinguish. As this seems still to be some niche, I'd thought it would be great to join forces 🧐

**Comment by bmalinconico** [comment]
Honestly i started developing this app in part because there wasn't a good way to get barcodes to BarcodeBuddy, they didn't have that app when I started. 

I also set out to fix some of the workflow difficulties I had, such as the increased number of barcode sources and a more streamlined product creation.
